INSERT INTO drawings (titulo, descripcion, imagen, dia_creacion, categoria) VALUES ('Retrato', 'Este retrato me lo pidió mi hermanito en Cristo José Merced quien lo obsequió a su hermana, en memoria de su padre que en paz descanse; sobre el dibujo se escribe un fragmento de una canción que solía cantarle a ella, "Gema" del compositor Güicho Cisneros: "Eres la gema que Dios convirtiera en mujer para bien de mi vida"... Un dibujo que inmortaliza su memoria y una canción que siempre traerá a la mente su recuerdo cuando se escuche...', 'https://firebasestorage.googleapis.com/v0/b/dibujos-2c099.appspot.com/o/Imagenes%2Fretrato.jpg?alt=media&token=62a85e26-5752-4454-b350-61ffde22509c', NOW(), 'Retrato');

INSERT INTO drawings (titulo, descripcion, imagen, dia_creacion, categoria) VALUES ('El Paraguas de Julieth', 'Éste método consiste en cubrir con óleo de 3 a 4 placas de vidrio, una con un color diferente, coloreamos encima de nuestro dibujo previamente trazado encima de cada placa una por una con sus respectivos colores, de tal modo que en el reverso se vaya creando una imagen hecha con óleo al momento de que el lápiz choca en el lienzo. Me encantó la paleta de color y el resultado.', 'https://firebasestorage.googleapis.com/v0/b/dibujos-2c099.appspot.com/o/Imagenes%2Fparaguas.jpg?alt=media&token=c648eceb-52c7-4d23-aebc-efe48be33daa', NOW(), 'Oleo');

INSERT INTO drawings (titulo, descripcion, imagen, dia_creacion, categoria) VALUES ('Catrina en campo de cempasúchil', 'El día de muertos, es un día muy especial para honrar a nuestros seres queridos que se han adelantado en el camino, no quería quedarme con las ganas de hacer algo representativo de esta hermosa tradición.', 'https://firebasestorage.googleapis.com/v0/b/dibujos-2c099.appspot.com/o/Imagenes%2Fcatrina.jpg?alt=media&token=7cf34178-21da-4f4d-a1ad-646b863857ee', NOW(), 'Personal');

INSERT INTO drawings (titulo, descripcion, imagen, dia_creacion, categoria) VALUES ('Sueño profundo en el jardín de mi alma', 'Una obra que expresa mi búsqueda de la plenitud, de mi lugar en el mundo, de ese jardín íntimo que necesito regar y cuidar más constantemente para sentirme completo', 'https://firebasestorage.googleapis.com/v0/b/dibujos-2c099.appspot.com/o/Imagenes%2F347429461_748162080648700_8505817646590060399_n.jpg?alt=media&token=c62b892f-8301-400c-8e39-67983923d32d', NOW(), 'Personal');

INSERT INTO drawings (titulo, descripcion, imagen, dia_creacion, categoria) VALUES ('Nebula de Guardianes de la Galaxia Vol. 3', 'Hace mucho que quería hacer un fanart o un retrato de Nebula, me encanta su personalidad y el gran desarrollo de personaje que ha tenido a lo largo de las películas, más que nada en esta tercera de los guardianes le han dado más protagonismo, más poderes y sobretodo una interacción más cercana y emotiva con los demás personajes lo que la vuelve para mí muy entrañable y genial, he aquí una experimentación, ya que casi no uso acuarelas, aunque últimamente las estoy practicando más', 'https://firebasestorage.googleapis.com/v0/b/dibujos-2c099.appspot.com/o/Imagenes%2Fnebula.jpg?alt=media&token=66ec6dbe-cf42-4083-9eea-16593c0a940f', NOW(), 'Personal');

INSERT INTO drawings (titulo, descripcion, imagen, dia_creacion, categoria) VALUES ('Sagrado Corazón de Jesús, en vos confío (Grabado en placa de acrílico)', 'Por mucho tiempo quería realizar una representación del Sagrado Corazón de Jesús, más allá de lo impresionante que se ve es su fuerza en mi vida, el amor Ágape de Jesucristo que es el amor más poderoso por excelencia, que perdona todo a pesar de tanto que le fallamos, que resplandeciente nos renueva y nos devuelve a la vida, un corazón que es ejemplo de una vida eterna que nos ayuda a llegar a la santidad.', 'https://firebasestorage.googleapis.com/v0/b/dibujos-2c099.appspot.com/o/Imagenes%2Fsagrado.jpg?alt=media&token=1f681128-cf31-4db0-be02-540a8009453c', NOW(), 'Acrilico');

INSERT INTO drawings (titulo, descripcion, imagen, dia_creacion, categoria) VALUES ('La ruta sin destino', '', 'https://firebasestorage.googleapis.com/v0/b/dibujos-2c099.appspot.com/o/Imagenes%2Fruta.jpg?alt=media&token=03e76f95-e75c-4b39-9753-8ecce1ea7de1', NOW(), 'Personal');

INSERT INTO drawings (titulo, descripcion, imagen, dia_creacion, categoria) VALUES ('Corazón artificial', '', 'https://firebasestorage.googleapis.com/v0/b/dibujos-2c099.appspot.com/o/Imagenes%2Fcorazon.jpg?alt=media&token=141b94e2-bb3c-43e0-aeec-85ba50a18930', NOW(), 'Personal');
